/**
 * ============================================================
 * PREVIA Core
 * Order HTTP Handler Test
 * ============================================================
 *
 * Tests the transport boundary:
 *
 * HTTP-like request
 *        ↓
 * OrderHttpHandler
 *        ↓
 * OrderEndpoint
 *        ↓
 * OrderService
 *        ↓
 * MemoryOrderRepository
 *
 * No real network.
 * No CMS.
 * No Google Sheets.
 *
 * ============================================================
 */

import {
  OrderService,
  OrderEndpoint,
  MemoryOrderRepository
} from "../../src/index.js";

import {
  OrderHttpHandler
} from "../../src/http/OrderHttpHandler.js";


console.log("=== PREVIA ORDER HTTP HANDLER TEST ===\n");


// ------------------------------------------------------------
// Setup
// ------------------------------------------------------------

const repository =
  new MemoryOrderRepository();

const orderService =
  new OrderService(repository);

const orderEndpoint =
  new OrderEndpoint(orderService);

const handler =
  new OrderHttpHandler(orderEndpoint);


// ------------------------------------------------------------
// TEST 1: Successful POST
// ------------------------------------------------------------

console.log("=== TEST 1: Successful POST ===");

const successResponse =
  await handler.create({

    method: "POST",

    body: {

  provider: "telegram",

  providerId: "123456789",

  telegram_name: "http_test_user",

  customer_name: "HTTP Test Customer",

  phone: "+380000000000",

  email: "http@test.com",

  payment_method: "card",

  items: [

        {
          sku: "W0098",
          title: "HTTP Test Watch",
          price: 175,
          quantity: 1
        }

      ]

    }

  });


console.log(
  "HTTP status:",
  successResponse.status
);

console.log(
  "Success:",
  successResponse.body.success
);

console.log(
  "Order ID:",
  successResponse.body.order_id
);


console.assert(
  successResponse.status === 200,
  "Successful request should return HTTP 200"
);

console.assert(
  successResponse.body.success === true,
  "Successful request should return success=true"
);

console.assert(
  typeof successResponse.body.order_id === "string",
  "Order ID should be generated by Core"
);

console.log(
  "✓ Successful POST works\n"
);


// ------------------------------------------------------------
// TEST 2: Validation Error
// ------------------------------------------------------------

console.log("=== TEST 2: Validation Error ===");

const validationResponse =
  await handler.create({

    method: "POST",

    body: {

      provider: "invalid-provider",

      customer_name: "Invalid Customer",

      items: []

    }

  });


console.log(
  "HTTP status:",
  validationResponse.status
);

console.log(
  "Success:",
  validationResponse.body.success
);

console.log(
  "Code:",
  validationResponse.body.code
);


console.assert(
  validationResponse.status === 400,
  "Validation error should return HTTP 400"
);

console.assert(
  validationResponse.body.success === false,
  "Validation error should return success=false"
);

console.assert(
  validationResponse.body.code === "VALIDATION_ERROR",
  "Validation error should map to VALIDATION_ERROR"
);

console.log(
  "✓ Validation mapping works\n"
);


// ------------------------------------------------------------
// TEST 3: Method Not Allowed
// ------------------------------------------------------------

console.log("=== TEST 3: Method Not Allowed ===");

const methodResponse =
  await handler.create({

    method: "GET",

    body: {}

  });


console.log(
  "HTTP status:",
  methodResponse.status
);

console.log(
  "Code:",
  methodResponse.body.code
);


console.assert(
  methodResponse.status === 405,
  "GET should return HTTP 405"
);

console.assert(
  methodResponse.body.code === "METHOD_NOT_ALLOWED",
  "GET should return METHOD_NOT_ALLOWED"
);

console.log(
  "✓ Method restriction works\n"
);


// ------------------------------------------------------------
// TEST 4: Repository Persistence
// ------------------------------------------------------------

console.log("=== TEST 4: Repository Persistence ===");

const storedOrder =
  await repository.findById(
    successResponse.body.order_id
  );


console.assert(
  storedOrder !== null,
  "Created order should exist in repository"
);

console.assert(
  storedOrder.order.order_id ===
    successResponse.body.order_id,
  "Stored order ID should match API response"
);

console.assert(
  storedOrder.items.length === 1,
  "Stored order should contain one item"
);


console.log(
  "Stored order ID:",
  storedOrder.order.order_id
);

console.log(
  "Stored items:",
  storedOrder.items.length
);

console.log(
  "✓ Repository persistence works\n"
);


// ------------------------------------------------------------
// FINAL
// ------------------------------------------------------------

console.log(
  "=== ALL ORDER HTTP HANDLER TESTS PASSED ==="
);
