const ERROR_CODES = Object.freeze({

  PRODUCT_INVALID: "PRODUCT_INVALID",

  SKU_REQUIRED: "SKU_REQUIRED",

  NAME_REQUIRED: "NAME_REQUIRED",

  PRICE_NEGATIVE: "PRICE_NEGATIVE",

  UNKNOWN_ENTITY: "UNKNOWN_ENTITY"

});

export {
  ERROR_CODES
};